### PR TITLE
Rows interface

### PR DESCRIPTION
**Pull request by thebho**
I needed a way mock the responses for the `AllDocs` and `Query` functions. This interface did the trick. 

This works when I use glide to switch out my branch for the `go-kivik` imports in my project, but I haven't been able to get your tests to run locally because of the import paths.

I can update the `RowsWrapper` name if you have a better idea.

### CODE REVIEW

**Comment by thebho** [comment]
It's private, but I'll try to sum it up.

```
var dataArray []DataType
rows, err := s.db.AllDocs(context.TODO(), options)
if err != nil {
	log.Printf("AllDocs: %v", err)
	return dataArray
}
for rows.Next() {
	var dataType DataType
	if err = rows.ScanDoc(&dataType); err != nil {
		log.Printf("ScanDoc: %v", err)
		continue
	}
	dataArray = append(dataArray, dataType)
}
```
I can easily mock the `AllDocs` function, but because the iter object inside of Rows is private it always fails in the test. I tried to expose the `*iter` but that was giving me issues.  Found it much easier to mock out the `Rows` type, and create my own iter logic. I use `moq` to create the struct and then implement the methods i need to mock in the test.

```
counter := 0
mockRows := &mocks.RowsWrapperMock{
	NextFunc: func() bool {
		counter++
		if counter > 1 {
			return false
		}
		return true
	},
	ScanDocFunc: func(in1 interface{}) error {
		return nil
	},
}
```
And then return that object when `AllDocs` is called

**Comment by flimzy** [comment]
Rather than mocking the top-level kivik types, would it be possible to create your own [driver.Driver](https://godoc.org/github.com/go-kivik/kivik/driver#Driver) type? This should give you all the flexibility you might want, without bothering with mocks.  Then for your tests, you'll just specify the name of your custom driver when calling `kivik.New`.

**Comment by thebho** [comment]
I'll give that a try

**Comment by thebho** [comment]
Thanks for the tip. The added layer of abstraction makes it a little more difficult to wire everything up, but I was able to create a mock Driver, Client, DB, and Rows and able to get the AllDocs unit tests to work. I might through something together for the wiki in case someone else is trying to build unit tests and runs across the same issue. 

```
vars (
	mockDriverDB *mocks.DBMock
	mockDB       *kivik.DB
	driverMock   *mocks.DriverMock
)

func init() {
	connectToMock()
}

func connectToMock() {
	mockDriverDB = new(mocks.DBMock)
	clientMock := &mocks.ClientMock{
		DBFunc: func(ctx context.Context, dbName string, options map[string]interface{}) (driver.DB, error) {
			return mockDriverDB, nil
		},
	}
	driverMock := &mocks.DriverMock{
		NewClientFunc: func(ctx context.Context, name string) (driver.Client, error) {
			return clientMock, nil
		},
	}
	kivik.Register("testing_mock", driverMock)
	client, err := kivik.New(context.TODO(), "testing_mock", "mock_url")
	if err != nil {
		panic(err)
	}
	db, err := client.DB(context.TODO(), "mock_db")
	if err != nil {
		panic(err)
	}
	mockDB = db
}
```
And then inside each test I can reference the mock driver DB and stub specific functions
```
	counter := 0
	mockRows := &mocks.RowsMock{
		NextFunc: func(row *driver.Row) error {
			counter++
			if counter > 1 {
				return errorMock
			}
			return nil
		},
		CloseFunc: func() error {
			return nil
		},
	}
	mockDriverDB.AllDocsFunc = func(ctx context.Context, options map[string]interface{}) (driver.Rows, error) {
		return mockRows, nil
	}
```

**Pull request closed without merging**
