### PR TITLE
_bulk_get support

### PR DESCRIPTION
**Pull request by fungiboletus**

### CODE REVIEW

**Comment by flimzy** [comment]
At a superficial glance, I think PouchDB does return the same format. See [docs](https://pouchdb.com/api.html#bulk_get).

My main motivation, though, is just to simplify the public API.  I'd rather put as much complexity as possible in the couchdb (or pouchdb) driver, and keep the API clean for the end-user.

As it comes to iterating through documents, the only meaningful difference I see is that the **_bulk_get** responses may contain an additional **_revisions** key (if `revs=true` is passed).  If that is indeed the only difference, then using `ScanDoc()` makes sense to me.

But I must admit, I've never used this endpoint, so there may be subtleties I'm missing. What is your opinion?

**Comment by fungiboletus** [comment]
It's slightly more different :

 * The list key is `results` instead of `docs` or `rows`.
 * Each result contains a array `docs` which contains as far as I know only one element which is an object with a single key, either `ok` or `error`, which then contain the document or the error.

I think it's a good idea to keep the API simple, I actually have a condition in my code to call `ScanDoc` or`ScanResult` and I would prefer to call only `ScanDoc`, but I'm not sure I have time to edit the pull-request to move the code inside the CouchDB driver because I'm not very familiar with the architecture of this project. So far I simply looked at the existing code to do the same.

**Comment by flimzy** [comment]
Thanks for the additional info.  Those differences are very important, but I think they can still be integrated into a `ScanDoc()` implementation. I'll see if I can work on that in the coming days.

**Comment by flimzy** [comment]
I have now added this support to Kivik, using the existing `ScanDoc` API. I'd love to hear how it works for you.

**Pull request closed without merging**
